import { ActivityLog, Client, Notification, SystemSettings, Task, User, Vehicle, VehicleDocument } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_admin_1',
    name: 'Anas (Admin)',
    email: 'admin@apexmotors.com',
    mobile: '+91 98470 00001',
    role: 'ADMIN',
    status: 'ACTIVE',
    createdAt: '2026-01-01T09:00:00Z',
    updatedAt: '2026-01-01T09:00:00Z',
  },
  {
    id: 'user_agent_rahman',
    name: 'Rahman (Agent)',
    email: 'rahman@apexmotors.com',
    mobile: '+91 98470 12345',
    role: 'AGENT',
    status: 'ACTIVE',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'user_agent_suresh',
    name: 'Suresh Kumar (Agent)',
    email: 'suresh@apexmotors.com',
    mobile: '+91 94470 54321',
    role: 'AGENT',
    status: 'ACTIVE',
    createdAt: '2026-01-15T11:00:00Z',
    updatedAt: '2026-01-15T11:00:00Z',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  companyName: 'Apex Motor Consultancy',
  companyMobile: '+91 98470 12345',
  companyAddress: 'Calicut Road, Perinthalmanna, Malappuram, Kerala 679322',
  defaultReminderDays: 30,
  supportedDocumentTypes: [
    'INSURANCE',
    'ROAD_TAX',
    'GREEN_TAX',
    'PUC',
    'FITNESS',
    'PERMIT',
    'RC',
    'OTHER',
  ],
};

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client_1',
    name: 'Mohammed Ali',
    mobile: '+91 98471 23456',
    alternateMobile: '+91 98471 99999',
    address: 'Baitul Noor, Bypass Road, Perinthalmanna, Kerala',
    email: 'mohammed.ali@example.com',
    assignedAgentId: 'user_agent_rahman',
    status: 'ACTIVE',
    notes: 'Premium client with multiple commercial and private vehicles.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'client_2',
    name: 'Fatima Zahra',
    mobile: '+91 97455 88990',
    alternateMobile: '',
    address: 'Green Meadows, Down Hill, Malappuram, Kerala',
    email: 'fatima.zahra@example.com',
    assignedAgentId: 'user_agent_rahman',
    status: 'ACTIVE',
    notes: 'Personal vehicles fleet.',
    createdBy: 'user_agent_rahman',
    createdAt: '2026-02-15T11:30:00Z',
    updatedAt: '2026-02-15T11:30:00Z',
  },
  {
    id: 'client_3',
    name: 'Rajesh Varma',
    mobile: '+91 94470 11223',
    alternateMobile: '+91 94470 33445',
    address: 'Varma Logistics, Mavoor Road, Kozhikode, Kerala',
    email: 'rajesh.varma@example.com',
    assignedAgentId: 'user_agent_suresh',
    status: 'ACTIVE',
    notes: 'Commercial transport operator with goods carriers.',
    createdBy: 'user_admin_1',
    createdAt: '2026-03-01T09:15:00Z',
    updatedAt: '2026-03-01T09:15:00Z',
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh_1',
    clientId: 'client_1',
    registrationNumber: 'KL-10-AB-1234',
    normalizedRegistrationNumber: 'KL10AB1234',
    vehicleType: 'PRIVATE_CAR',
    vehicleClass: 'Motor Car (LMV)',
    make: 'Toyota',
    model: 'Innova Crysta',
    variant: '2.4 VX 7-Seater',
    fuelType: 'DIESEL',
    manufacturingYear: 2021,
    registrationDate: '2021-04-12',
    chassisNumber: 'MBJ11BB4001234567',
    engineNumber: '2GDF9876543',
    rto: 'KL-10 Perinthalmanna',
    registrationValidity: '2036-04-11',
    assignedAgentId: 'user_agent_rahman',
    status: 'ACTIVE',
    notes: 'Family car in excellent condition. High priority renewals.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-01T10:30:00Z',
    updatedAt: '2026-02-01T10:30:00Z',
  },
  {
    id: 'veh_2',
    clientId: 'client_1',
    registrationNumber: 'KL-10-CD-5678',
    normalizedRegistrationNumber: 'KL10CD5678',
    vehicleType: 'COMMERCIAL_TAXI',
    vehicleClass: 'Motor Cab (LMV)',
    make: 'Maruti Suzuki',
    model: 'Dzire Tour',
    variant: 'VXI CNG',
    fuelType: 'CNG',
    manufacturingYear: 2022,
    registrationDate: '2022-08-20',
    chassisNumber: 'MA3EAA12S00998877',
    engineNumber: 'K12N882211',
    rto: 'KL-10 Perinthalmanna',
    registrationValidity: '2037-08-19',
    assignedAgentId: 'user_agent_rahman',
    status: 'ACTIVE',
    notes: 'Airport taxi vehicle.',
    createdBy: 'user_agent_rahman',
    createdAt: '2026-02-05T14:00:00Z',
    updatedAt: '2026-02-05T14:00:00Z',
  },
  {
    id: 'veh_3',
    clientId: 'client_1',
    registrationNumber: 'KL-11-EF-9999',
    normalizedRegistrationNumber: 'KL11EF9999',
    vehicleType: 'GOODS_CARRIER',
    vehicleClass: 'Goods Carrier (LGV)',
    make: 'Ashok Leyland',
    model: 'Bada Dost',
    variant: 'i4 Diesel',
    fuelType: 'DIESEL',
    manufacturingYear: 2023,
    registrationDate: '2023-01-10',
    chassisNumber: 'MB1DCA34N00112233',
    engineNumber: 'P15F773344',
    rto: 'KL-11 Kozhikode',
    registrationValidity: '2038-01-09',
    assignedAgentId: 'user_agent_rahman',
    status: 'ACTIVE',
    notes: 'Commercial delivery van.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-10T12:00:00Z',
    updatedAt: '2026-02-10T12:00:00Z',
  },
  {
    id: 'veh_4',
    clientId: 'client_2',
    registrationNumber: 'KL-55-XY-4321',
    normalizedRegistrationNumber: 'KL55XY4321',
    vehicleType: 'PRIVATE_CAR',
    vehicleClass: 'Motor Car (Electric)',
    make: 'Tata',
    model: 'Nexon EV',
    variant: 'Empowered Plus LR',
    fuelType: 'ELECTRIC',
    manufacturingYear: 2024,
    registrationDate: '2024-03-15',
    chassisNumber: 'MAT625000R1234567',
    engineNumber: 'EM543210',
    rto: 'KL-55 Tirur',
    registrationValidity: '2039-03-14',
    assignedAgentId: 'user_agent_rahman',
    status: 'ACTIVE',
    notes: 'Electric SUV. Road tax exemption verified.',
    createdBy: 'user_agent_rahman',
    createdAt: '2026-02-15T12:00:00Z',
    updatedAt: '2026-02-15T12:00:00Z',
  },
  {
    id: 'veh_5',
    clientId: 'client_3',
    registrationNumber: 'KL-07-ZZ-7788',
    normalizedRegistrationNumber: 'KL07ZZ7788',
    vehicleType: 'GOODS_CARRIER',
    vehicleClass: 'Heavy Goods Vehicle',
    make: 'Tata',
    model: 'Signa 2823.K',
    variant: 'Tipper',
    fuelType: 'DIESEL',
    manufacturingYear: 2020,
    registrationDate: '2020-06-10',
    chassisNumber: 'MAT445000P9988776',
    engineNumber: 'CUMMINS6BT9911',
    rto: 'KL-07 Ernakulam',
    registrationValidity: '2035-06-09',
    assignedAgentId: 'user_agent_suresh',
    status: 'ACTIVE',
    notes: 'Heavy quarry tipper. Fitness and National Permit inspections required annually.',
    createdBy: 'user_admin_1',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
  },
];

// Reference date helper to create dynamic relative dates (e.g. today, overdue 3 days, due in 10 days)
const todayObj = new Date();
const formatDateOffset = (days: number): string => {
  const d = new Date(todayObj);
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

export const INITIAL_DOCUMENTS: VehicleDocument[] = [
  // KL-10-AB-1234 (Toyota Innova)
  {
    id: 'doc_1',
    vehicleId: 'veh_1',
    clientId: 'client_1',
    documentType: 'INSURANCE',
    documentNumber: 'POL-2025-981244',
    startDate: formatDateOffset(-355),
    expiryDate: formatDateOffset(10), // DUE SOON in 10 days
    insuranceProvider: 'Oriental Insurance Co.',
    policyType: 'COMPREHENSIVE',
    amount: 28450,
    reminderDays: 30,
    status: 'DUE_SOON',
    fileName: 'innova_insurance_policy_2025_26.pdf',
    fileUrl: '/sample-docs/innova_insurance.pdf',
    notes: 'Zero depreciation with engine protect add-on. Client requested renewal quotation from GoDigit and Oriental.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-02-01T11:00:00Z',
  },
  {
    id: 'doc_2',
    vehicleId: 'veh_1',
    clientId: 'client_1',
    documentType: 'PUC',
    documentNumber: 'PUC-KL10-2025-881',
    issueDate: formatDateOffset(-182),
    expiryDate: formatDateOffset(-3), // OVERDUE by 3 days!
    testingCentre: 'Perinthalmanna Green Fuel Check Centre',
    amount: 150,
    reminderDays: 15,
    status: 'OVERDUE',
    fileName: 'innova_puc_cert.pdf',
    fileUrl: '/sample-docs/innova_puc.pdf',
    notes: 'PUC expired 3 days ago. Needs urgent follow-up to avoid traffic challan.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-01T11:15:00Z',
    updatedAt: '2026-02-01T11:15:00Z',
  },
  {
    id: 'doc_3',
    vehicleId: 'veh_1',
    clientId: 'client_1',
    documentType: 'ROAD_TAX',
    documentNumber: 'TAX-KL10-2021-9988',
    lastPaymentDate: '2021-04-12',
    validityValue: 15,
    validityUnit: 'YEARS',
    expiryDate: '2036-04-11',
    amount: 145000,
    reminderDays: 60,
    status: 'ACTIVE',
    fileName: 'one_time_tax_receipt.pdf',
    fileUrl: '/sample-docs/innova_tax.pdf',
    notes: 'One-time 15 years Kerala State Motor Vehicle Tax paid at registration.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-01T11:20:00Z',
    updatedAt: '2026-02-01T11:20:00Z',
  },
  {
    id: 'doc_4',
    vehicleId: 'veh_1',
    clientId: 'client_1',
    documentType: 'GREEN_TAX',
    documentNumber: 'GT-KL10-2026-112',
    lastPaymentDate: '2026-01-10',
    validityValue: 5,
    validityUnit: 'YEARS',
    expiryDate: '2031-01-09',
    amount: 1000,
    reminderDays: 30,
    status: 'ACTIVE',
    notes: 'Green tax valid for 5 years.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-01T11:25:00Z',
    updatedAt: '2026-02-01T11:25:00Z',
  },
  {
    id: 'doc_5',
    vehicleId: 'veh_1',
    clientId: 'client_1',
    documentType: 'RC',
    documentNumber: 'RC-KL10-2021-0412',
    issueDate: '2021-04-12',
    expiryDate: '2036-04-11',
    amount: 0,
    reminderDays: 60,
    status: 'ACTIVE',
    fileName: 'innova_rc_smartcard.pdf',
    fileUrl: '/sample-docs/innova_rc.pdf',
    notes: 'Original smart card RC with owner.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-01T11:30:00Z',
    updatedAt: '2026-02-01T11:30:00Z',
  },

  // KL-10-CD-5678 (Dzire Commercial Taxi)
  {
    id: 'doc_6',
    vehicleId: 'veh_2',
    clientId: 'client_1',
    documentType: 'FITNESS',
    documentNumber: 'FC-KL10-2025-7712',
    issueDate: formatDateOffset(-360),
    expiryDate: formatDateOffset(0), // DUE TODAY!
    fitnessType: 'Commercial Light Passenger Vehicle',
    amount: 1200,
    reminderDays: 30,
    status: 'DUE_TODAY',
    fileName: 'dzire_fitness_certificate.pdf',
    notes: 'Annual fitness inspection slot booked at Perinthalmanna Sub-RTO for today.',
    createdBy: 'user_agent_rahman',
    createdAt: '2026-02-05T14:30:00Z',
    updatedAt: '2026-02-05T14:30:00Z',
  },
  {
    id: 'doc_7',
    vehicleId: 'veh_2',
    clientId: 'client_1',
    documentType: 'PERMIT',
    documentNumber: 'PER-TAXI-KL10-2024',
    issueDate: formatDateOffset(-300),
    expiryDate: formatDateOffset(65),
    permitType: 'All Kerala Contract Carriage Taxi Permit',
    amount: 5500,
    reminderDays: 30,
    status: 'ACTIVE',
    notes: '5-year permit renewal scheduled next year.',
    createdBy: 'user_agent_rahman',
    createdAt: '2026-02-05T14:35:00Z',
    updatedAt: '2026-02-05T14:35:00Z',
  },

  // KL-11-EF-9999 (Goods Carrier)
  {
    id: 'doc_8',
    vehicleId: 'veh_3',
    clientId: 'client_1',
    documentType: 'ROAD_TAX',
    documentNumber: 'TAX-QTR-KL11-9999',
    lastPaymentDate: formatDateOffset(-85),
    expiryDate: formatDateOffset(5), // DUE SOON in 5 days!
    validityValue: 3,
    validityUnit: 'MONTHS',
    amount: 3200,
    reminderDays: 15,
    status: 'DUE_SOON',
    notes: 'Quarterly goods vehicle tax due on 5th of this month.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-10T12:30:00Z',
    updatedAt: '2026-02-10T12:30:00Z',
  },

  // KL-07-ZZ-7788 (Tata Heavy Tipper - Suresh's client)
  {
    id: 'doc_9',
    vehicleId: 'veh_5',
    clientId: 'client_3',
    documentType: 'FITNESS',
    documentNumber: 'FC-KL07-2025-1100',
    issueDate: formatDateOffset(-370),
    expiryDate: formatDateOffset(-5), // OVERDUE by 5 days
    fitnessType: 'Heavy Commercial Goods Vehicle',
    amount: 3800,
    reminderDays: 30,
    status: 'OVERDUE',
    notes: 'Heavy commercial fitness inspection pending smoke test and speed governor calibration.',
    createdBy: 'user_agent_suresh',
    createdAt: '2026-03-01T10:30:00Z',
    updatedAt: '2026-03-01T10:30:00Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_1',
    clientId: 'client_1',
    vehicleId: 'veh_1',
    documentId: 'doc_1',
    title: 'Insurance Renewal Follow-up: Innova KL-10-AB-1234',
    description: 'Call Mohammed Ali regarding Oriental Insurance policy expiring in 10 days. Send premium quote and NCB discount options.',
    assignedTo: 'user_agent_rahman',
    dueDate: formatDateOffset(5),
    status: 'PENDING',
    priority: 'HIGH',
    notes: 'Client prefers digital payment and policy delivered via WhatsApp.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-01T12:00:00Z',
    updatedAt: '2026-02-01T12:00:00Z',
  },
  {
    id: 'task_2',
    clientId: 'client_1',
    vehicleId: 'veh_1',
    documentId: 'doc_2',
    title: 'Urgent PUC Emission Test: Innova KL-10-AB-1234',
    description: 'PUC is already overdue. Remind client immediately to visit nearby test center to avoid penalty.',
    assignedTo: 'user_agent_rahman',
    dueDate: formatDateOffset(0),
    status: 'CLIENT_CONTACTED',
    priority: 'HIGH',
    notes: 'Called Mohammed Ali today morning. He agreed to take vehicle to Perinthalmanna test center by 4 PM.',
    createdBy: 'user_admin_1',
    createdAt: '2026-02-01T12:30:00Z',
    updatedAt: '2026-02-01T12:30:00Z',
  },
  {
    id: 'task_3',
    clientId: 'client_1',
    vehicleId: 'veh_2',
    documentId: 'doc_6',
    title: 'RTO Fitness Test Inspection: Dzire Taxi KL-10-CD-5678',
    description: 'Coordinate physical vehicle inspection at RTO ground today. Check speed limiter and meter seal.',
    assignedTo: 'user_agent_rahman',
    dueDate: formatDateOffset(0),
    status: 'PROCESSING',
    priority: 'HIGH',
    notes: 'Driver arrived at RTO testing track. Assistant waiting for Motor Vehicle Inspector.',
    createdBy: 'user_agent_rahman',
    createdAt: '2026-02-05T15:00:00Z',
    updatedAt: '2026-02-05T15:00:00Z',
  },
  {
    id: 'task_4',
    clientId: 'client_3',
    vehicleId: 'veh_5',
    documentId: 'doc_9',
    title: 'Overdue Fitness Renewal: Tipper KL-07-ZZ-7788',
    description: 'Heavy vehicle fitness expired 5 days ago. Client needs assistance with speed governor re-certification.',
    assignedTo: 'user_agent_suresh',
    dueDate: formatDateOffset(1),
    status: 'PENDING',
    priority: 'HIGH',
    notes: 'Client promised vehicle would be brought from quarry on Friday.',
    createdBy: 'user_admin_1',
    createdAt: '2026-03-01T11:00:00Z',
    updatedAt: '2026-03-01T11:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    userId: 'user_agent_rahman',
    title: 'PUC Overdue Alert',
    message: 'Pollution certificate for KL-10-AB-1234 (Mohammed Ali) expired 3 days ago.',
    type: 'OVERDUE',
    relatedVehicleId: 'veh_1',
    isRead: false,
    createdAt: '2026-02-01T08:30:00Z',
  },
  {
    id: 'notif_2',
    userId: 'user_agent_rahman',
    title: 'Fitness Due Today',
    message: 'Fitness inspection for taxi KL-10-CD-5678 is scheduled for today.',
    type: 'RENEWAL_DUE',
    relatedVehicleId: 'veh_2',
    isRead: false,
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'notif_3',
    userId: 'user_admin_1',
    title: 'Quarterly Road Tax Due Soon',
    message: 'Quarterly Road Tax for Goods Carrier KL-11-EF-9999 due in 5 days.',
    type: 'RENEWAL_DUE',
    relatedVehicleId: 'veh_3',
    isRead: false,
    createdAt: '2026-02-01T09:15:00Z',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log_1',
    userId: 'user_admin_1',
    userName: 'Anas (Admin)',
    action: 'CLIENT_CREATED',
    entityType: 'CLIENT',
    entityId: 'client_1',
    description: 'Created new client record for Mohammed Ali with 3 vehicles.',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'log_2',
    userId: 'user_admin_1',
    userName: 'Anas (Admin)',
    action: 'VEHICLE_CREATED',
    entityType: 'VEHICLE',
    entityId: 'veh_1',
    description: 'Registered vehicle Toyota Innova Crysta (KL-10-AB-1234).',
    createdAt: '2026-02-01T10:30:00Z',
  },
  {
    id: 'log_3',
    userId: 'user_agent_rahman',
    userName: 'Rahman (Agent)',
    action: 'TASK_UPDATED',
    entityType: 'TASK',
    entityId: 'task_2',
    description: 'Updated PUC renewal task to CLIENT_CONTACTED. Client will visit test center.',
    createdAt: '2026-02-01T12:35:00Z',
  },
];
